# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

trigger:
- master
steps:
- script: dotnet publish DogeNetCoreApi/DogeNetCoreApi/DogeNetCoreApi.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish $(buildConfiguration) to $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
